# █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
#
#                                ██        ██                     ▄▄
#                                ▀▀        ▀▀                     ██
#                              ████      ████                ▄███▄██   ▄████▄   ██▄  ▄██
#                                ██        ██               ██▀  ▀██  ██▄▄▄▄██   ██  ██
#                                ██        ██      █████    ██    ██  ██▀▀▀▀▀▀   ▀█▄▄█▀
#                                ██        ██               ▀██▄▄███  ▀██▄▄▄▄█    ████
#                                ██        ██                 ▀▀▀ ▀▀    ▀▀▀▀▀      ▀▀
#                             ████▀     ████▀
#
# █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
# █████████████████████████████████████████ .github/ISSUE_TEMPLATE/config.yml █████████████████████████████████████████
#
# GitHub issue-template chooser config. Disables blank issues so reporters pick a structured template.
#
# █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

blank_issues_enabled: false
